# Generated by Django 5.2.17 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher_redeem_code',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_status',
            field=models.CharField(
                choices=[('NEW', 'New'), ('REDEEMED', 'Redeemed')],
                default='NEW',
                max_length=16,
            ),
        ),
    ]
